AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The certification login API
  
Globals:
  Function:
    Runtime: nodejs12.x
    CodeUri: ../../../src/
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.helloHandler
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

  SwansdomFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.swansdomHandler
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /swansdom
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: 
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SwansdomApi:
    Description: "API Gateway endpoint URL for Prod stage for Swansdom function"
    Value: 
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/swansdom/"

  